USE puntonet_pos;
SET FOREIGN_KEY_CHECKS=0; TRUNCATE TABLE insumos; SET FOREIGN_KEY_CHECKS=1;
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-10', 104.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-12', 108.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-14', 108.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-16', 112.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-6', 101.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-8', 104.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-L', 119.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-M', 119.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-S', 112.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-XL', 122.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-10', 41.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-12', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-14', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-16', 48.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-6', 38.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-8', 41.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-L', 53.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-M', 53.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-S', 48.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-XL', 56.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-10', 39.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-12', 41.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-14', 41.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-16', 42.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-6', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-8', 39.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-L', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-M', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-S', 42.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-XL', 47.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-S', 70.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-8', 65.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-M', 74.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (6, 1, 'Corbata - Elástico grande', 15.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (6, 1, 'Corbata - Elástico pequeña', 13.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (6, 1, 'Corbata - Larga de nudo', 17.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-10', 73.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-12', 73.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-14', 75.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-16', 75.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-8', 70.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-L', 80.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-M', 80.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (9, 1, 'Falda T-S', 77.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (2, 1, 'Pack b - 4° primaria', 135.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-10', 58.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-12', 62.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-14', 62.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-16', 65.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-6', 56.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-8', 58.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-L', 68.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-M', 68.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-S', 65.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-XL', 72.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-10', 53.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-12', 53.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-14', 53.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-16', 57.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-6', 50.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-8', 50.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-32', 60.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-30', 60.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (11, 1, 'Pantalón Vestir T-28', 60.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-10', 33.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-12', 36.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-14', 36.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-16', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-6', 31.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-8', 33.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-L', 39.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-M', 39.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-S', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-XL', 41.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-10', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-12', 40.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-14', 40.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-16', 43.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-6', 35.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-8', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-L', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-M', 45.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-S', 43.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (14, 1, 'Short Inicial T-10', 63.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (14, 1, 'Short Inicial T-6', 60.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (14, 1, 'Short Inicial T-8', 63.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (10, 1, 'Pantaloneta Educ.Física T-4', 56.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (4, 1, 'Camisa unisex T-4', 37.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (3, 1, 'Camipolo T-4', 38.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (12, 1, 'Polo Educ.Física T-4', 31.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (1, 1, 'Buzo Educ.Física T-4', 101.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-4', 63.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-6', 63.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-10', 65.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-12', 67.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-14', 67.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-16', 70.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-L', 74.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (5, 1, 'Casaca Educ.Física T-XL', 76.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (13, 1, 'Short Educ.Física T-4', 35.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (14, 1, 'Short Inicial T-4', 60.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Inglés - 1° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Inglés - 2° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Inglés - 3° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Inglés - 4° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Inglés - 5° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Inglés - 6° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Inglés - 1° Sec', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Inglés - 2° Sec', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Inglés - 3° Sec', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Inglés - 4° Sec', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Inglés - 5° Sec', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Computación - 1° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Computación - 2° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'Computación - 3° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Computación - 4° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Computación - 5° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'Computación - 6° Prim', 30.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'CYA/PS - 1° Prim', 14.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'CYA/PS - 2° Prim', 14.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (15, 1, 'CYA/PS - 3° Prim', 14.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'HP/Geo/Bio - 4° Prim', 21.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'HP/Geo/Bio - 5° Prim', 21.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (16, 1, 'HP/Geo/Bio - 6° Prim', 21.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Fis/Qui/Bio/CPT - 1° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Fis/Qui/Bio/CPT - 2° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Fis/Qui/Bio/CPT - 3° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Fis/Qui/Bio/CPT - 4° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'Fis/Qui/Bio/CPT - 5° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'HP/HU/Geo/DPCC - 1°Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'HP/HU/Geo/DPCC - 2° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'HP/HU/Geo/DPCC - 3° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'HP/HU/Geo/DPCC - 4° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (17, 1, 'HP/HU/Geo/DPCC - 5° Sec', 29.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (2, 1, 'Envio S/5.00', 5.0, 0, 0, 1, NULL);
INSERT INTO insumos (id_categoria, id_unidad, nombre, precio_unitario, costo_produccion, stock_piezas, estado, id_talla) VALUES (2, 1, 'Envio S/10.00', 10.0, 0, 0, 1, NULL);
